name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  all:
    if: always()
    name: all-jobs
    runs-on: ubuntu-latest
    needs:
      - build
      - release
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            *.tar.xz
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - { config: x86_64-linux }

    container:
      image: ghcr.io/benjaminkern/ci-images/ubuntu/20.04:main
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v4
      - name: Init
        run: ct-ng --version
